import React, { useState, useEffect } from 'react';
import { useParams } from 'react-router-dom';
import { api } from '../../../../infrastructure/api';
import { Layers, ChevronLeft, ChevronRight, RotateCw } from 'lucide-react';
import { cn } from '../../../../design-system/utils';

export const FlashcardsPanel: React.FC = () => {
  const { lectureId } = useParams();
  const [flashcards, setFlashcards] = useState<any>(null);
  const [loading, setLoading] = useState(true);
  const [currentIndex, setCurrentIndex] = useState(0);
  const [isFlipped, setIsFlipped] = useState(false);

  useEffect(() => {
    const fetchFlashcards = async () => {
      try {
        const { data } = await api.get(`/api/lectures/${lectureId}/flashcards`);
        setFlashcards(data.data);
      } catch (err) {
        console.log('Flashcards not ready or missing');
      } finally {
        setLoading(false);
      }
    };
    fetchFlashcards();
  }, [lectureId]);

  // Handle keyboard navigation
  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      if (!flashcards || !flashcards.cards || flashcards.cards.length === 0) return;
      
      if (e.key === 'ArrowRight') {
        nextCard();
      } else if (e.key === 'ArrowLeft') {
        prevCard();
      } else if (e.key === ' ' || e.key === 'ArrowUp' || e.key === 'ArrowDown') {
        e.preventDefault();
        setIsFlipped(prev => !prev);
      }
    };

    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, [flashcards, currentIndex]);

  if (loading) return <div className="text-sm text-muted-foreground animate-pulse p-4">Loading flashcards...</div>;
  if (!flashcards || !flashcards.cards || flashcards.cards.length === 0) {
    return (
      <div className="p-4 bg-card border border-border rounded-xl">
        <h3 className="font-semibold mb-2 flex items-center"><Layers className="w-4 h-4 mr-2"/> Flashcards</h3>
        <p className="text-sm text-muted-foreground">Study cards are still being generated by the AI.</p>
      </div>
    );
  }

  const cards = flashcards.cards;

  const nextCard = () => {
    setIsFlipped(false);
    setTimeout(() => {
      setCurrentIndex((prev) => (prev + 1) % cards.length);
    }, 150); // Small delay so it doesn't swap text before flipping back
  };

  const prevCard = () => {
    setIsFlipped(false);
    setTimeout(() => {
      setCurrentIndex((prev) => (prev - 1 + cards.length) % cards.length);
    }, 150);
  };

  return (
    <div className="bg-card border border-border rounded-xl p-6 shadow-sm">
      <div className="flex items-center justify-between mb-6">
        <h3 className="text-lg font-bold flex items-center">
          <Layers className="w-5 h-5 mr-2 text-primary"/> 
          Study Cards
        </h3>
        <span className="text-sm font-medium text-primary bg-primary/10 px-3 py-1 rounded-full border border-primary/20">
          {currentIndex + 1} / {cards.length}
        </span>
      </div>

      {/* The 3D flip card container */}
      <div className="relative w-full h-[320px] perspective-1000 group cursor-pointer" onClick={() => setIsFlipped(!isFlipped)}>
        <div className={cn(
          "w-full h-full absolute transition-transform duration-700 preserve-3d ease-[cubic-bezier(0.23,1,0.32,1)]",
          isFlipped ? "rotate-y-180" : ""
        )}>
          {/* Front */}
          <div className="absolute w-full h-full backface-hidden bg-gradient-to-br from-primary/20 via-purple-500/10 to-transparent backdrop-blur-md border border-primary/30 rounded-2xl flex flex-col items-center justify-center p-8 text-center shadow-[0_0_40px_-10px_rgba(59,130,246,0.3)]">
            <div className="flex-1 flex items-center justify-center overflow-y-auto hide-scrollbar w-full">
              <h4 className="text-2xl font-bold text-foreground drop-shadow-md leading-relaxed">{cards[currentIndex].front}</h4>
            </div>
            <div className="absolute bottom-5 right-5 text-primary/60 animate-pulse flex items-center gap-2">
              <span className="text-xs font-semibold uppercase tracking-widest">Flip</span>
              <RotateCw className="w-4 h-4" />
            </div>
          </div>
          
          {/* Back */}
          <div className="absolute w-full h-full backface-hidden rotate-y-180 bg-gradient-to-tr from-emerald-500/15 via-primary/5 to-transparent backdrop-blur-md border border-emerald-500/30 rounded-2xl flex flex-col items-center justify-center p-8 text-center shadow-[0_0_40px_-10px_rgba(16,185,129,0.2)]">
            <div className="flex-1 flex items-center justify-center overflow-y-auto w-full pr-2">
              <p className="text-lg font-medium text-foreground/90 leading-relaxed">{cards[currentIndex].back}</p>
            </div>
          </div>
        </div>
      </div>

      <div className="flex items-center justify-between mt-6">
        <button 
          onClick={(e) => { e.stopPropagation(); prevCard(); }}
          className="p-2 border border-border rounded-full hover:bg-surfaceHover transition-colors"
        >
          <ChevronLeft className="w-5 h-5" />
        </button>
        <p className="text-xs text-muted-foreground">Space to flip, arrows to navigate</p>
        <button 
          onClick={(e) => { e.stopPropagation(); nextCard(); }}
          className="p-2 border border-border rounded-full hover:bg-surfaceHover transition-colors"
        >
          <ChevronRight className="w-5 h-5" />
        </button>
      </div>
    </div>
  );
};
