import React, { useState, useEffect } from 'react';
import { useParams } from 'react-router-dom';
import { api } from '../../../../infrastructure/api';
import { CheckCircle2, XCircle, BrainCircuit } from 'lucide-react';
import { cn } from '../../../../design-system/utils';

export const QuizPanel: React.FC = () => {
  const { lectureId } = useParams();
  const [quiz, setQuiz] = useState<any>(null);
  const [loading, setLoading] = useState(true);
  const [answers, setAnswers] = useState<Record<string, number>>({});
  const [submitted, setSubmitted] = useState(false);

  useEffect(() => {
    const fetchQuiz = async () => {
      try {
        const { data } = await api.get(`/api/lectures/${lectureId}/quiz`);
        setQuiz(data.data);
      } catch (err) {
        // Handle gracefully if not generated yet
        console.log('Quiz not ready or missing');
      } finally {
        setLoading(false);
      }
    };
    fetchQuiz();
  }, [lectureId]);

  if (loading) return <div className="text-sm text-muted-foreground animate-pulse p-4">Loading quiz...</div>;
  if (!quiz || !quiz.questions || quiz.questions.length === 0) {
    return (
      <div className="p-4 bg-card border border-border rounded-xl">
        <h3 className="font-semibold mb-2 flex items-center"><BrainCircuit className="w-4 h-4 mr-2"/> Knowledge Check</h3>
        <p className="text-sm text-muted-foreground">Quiz is still being generated by the AI, or wasn't created for this lecture.</p>
      </div>
    );
  }

  const handleSelect = (questionId: string, optionIndex: number) => {
    if (submitted) return;
    setAnswers(prev => ({ ...prev, [questionId]: optionIndex }));
  };

  const calculateScore = () => {
    let score = 0;
    quiz.questions.forEach((q: any) => {
      if (answers[q.id] === q.answerIndex) score++;
    });
    return score;
  };

  return (
    <div className="bg-card border border-border rounded-xl p-6 shadow-sm">
      <h3 className="text-lg font-bold mb-4 flex items-center">
        <BrainCircuit className="w-5 h-5 mr-2 text-primary"/> 
        Knowledge Check
      </h3>

      <div className="space-y-8">
        {quiz.questions.map((q: any, idx: number) => {
          const isCorrect = answers[q.id] === q.answerIndex;

          return (
            <div key={q.id} className="space-y-3">
              <p className="font-medium text-foreground">
                <span className="text-muted-foreground mr-2">{idx + 1}.</span>
                {q.question}
              </p>
              
              <div className="space-y-2 pl-6">
                {q.options.map((opt: string, optIdx: number) => {
                  const isSelected = answers[q.id] === optIdx;
                  const isCorrectOption = q.answerIndex === optIdx;
                  
                  let optStyle = "border-border hover:border-primary/50 text-foreground cursor-pointer";
                  if (submitted) {
                    optStyle = "border-border cursor-default opacity-60";
                    if (isCorrectOption) optStyle = "border-green-500 bg-green-500/10 text-green-700 dark:text-green-400 opacity-100";
                    else if (isSelected && !isCorrectOption) optStyle = "border-red-500 bg-red-500/10 text-red-700 dark:text-red-400 opacity-100";
                  } else if (isSelected) {
                    optStyle = "border-primary bg-primary/5 text-primary";
                  }

                  return (
                    <div 
                      key={optIdx}
                      onClick={() => handleSelect(q.id, optIdx)}
                      className={cn("p-3 rounded-lg border transition-all text-sm flex items-center justify-between", optStyle)}
                    >
                      <span>{opt}</span>
                      {submitted && isCorrectOption && <CheckCircle2 className="w-4 h-4 text-green-500" />}
                      {submitted && isSelected && !isCorrectOption && <XCircle className="w-4 h-4 text-red-500" />}
                    </div>
                  );
                })}
              </div>

              {submitted && (
                <div className={cn("pl-6 text-sm p-3 rounded-lg mt-2", isCorrect ? "bg-green-500/10 text-green-700 dark:text-green-400" : "bg-red-500/10 text-red-700 dark:text-red-400")}>
                  <strong>Explanation:</strong> {q.explanation}
                </div>
              )}
            </div>
          );
        })}
      </div>

      <div className="mt-8 pt-6 border-t border-border">
        {!submitted ? (
          <button 
            onClick={() => setSubmitted(true)}
            disabled={Object.keys(answers).length < quiz.questions.length}
            className="w-full bg-primary text-primary-foreground py-2 rounded-lg font-medium disabled:opacity-50 transition-colors"
          >
            Submit Quiz
          </button>
        ) : (
          <div className="text-center">
            <p className="text-2xl font-bold mb-2">Score: {calculateScore()} / {quiz.questions.length}</p>
            <button 
              onClick={() => { setSubmitted(false); setAnswers({}); }}
              className="mt-4 px-4 py-2 border border-border rounded-lg text-sm font-medium hover:bg-surfaceHover transition-colors"
            >
              Retry Quiz
            </button>
          </div>
        )}
      </div>
    </div>
  );
};
