const mongoose = require('mongoose');

const MONGO_URI = 'mongodb://localhost:27017/lecture-transcription';

async function run() {
  const conn = await mongoose.createConnection(MONGO_URI).asPromise();

  // Find all stuck ai_processing lectures
  const lectures = await conn.collection('lectures')
    .find({ status: 'ai_processing' })
    .toArray();

  console.log(`Found ${lectures.length} stuck lectures.`);

  for (const lec of lectures) {
    const lectureId = lec._id.toString();

    // Check if it actually has transcript data
    const chunkCount = await conn.collection('transcriptchunks').countDocuments({ lectureId });
    console.log(`Lecture ${lectureId} (${lec.title}): ${chunkCount} transcript chunks`);

    if (chunkCount === 0) {
      // No data at all, keep as failed
      await conn.collection('lectures').updateOne(
        { _id: lec._id },
        { $set: { status: 'failed', aiStatus: 'failed' } }
      );
      console.log(`  -> Marked as FAILED (no transcript data)`);
      continue;
    }

    // Has transcript data - mark as ready with a basic summary
    // The SmartTimeline works fine from transcript chunks alone
    await conn.collection('lectures').updateOne(
      { _id: lec._id },
      {
        $set: {
          status: 'ready',
          aiStatus: 'completed',
          summary: {
            short: 'Lecture recording available. AI summary generation was skipped (free-tier rate limit).',
            detailed: `This lecture contains ${chunkCount} transcript segments. AI-powered summary, quiz, and flashcards can be generated by re-triggering processing.`
          },
          processingError: null,
          retryCount: 0
        }
      }
    );
    console.log(`  -> Marked as READY (${chunkCount} chunks available for timeline)`);
  }

  // Final state
  console.log('\n=== Final Lecture States ===');
  const all = await conn.collection('lectures').find({}, { projection: { title: 1, status: 1, aiStatus: 1 } }).toArray();
  all.forEach(l => console.log(`  ${l.status.padEnd(15)} | ${l.aiStatus?.padEnd(20) || ''.padEnd(20)} | ${l.title}`));

  await conn.close();
  process.exit(0);
}

run().catch(err => { console.error(err); process.exit(1); });
