import puppeteer from 'puppeteer';
import { generateLecturePdfHtml, PdfTemplateData } from './lecture-pdf.template';

export class PdfService {
  /**
   * Generates a PDF buffer from lecture data using Puppeteer.
   */
  static async generateStudyPackPdf(data: PdfTemplateData): Promise<Buffer> {
    const htmlContent = generateLecturePdfHtml(data);
    
    // Launch headless browser
    const browser = await puppeteer.launch({
      headless: true,
      args: ['--no-sandbox', '--disable-setuid-sandbox', '--disable-dev-shm-usage']
    });

    try {
      const page = await browser.newPage();
      
      // Set content and wait for network to be idle
      await page.setContent(htmlContent, { waitUntil: 'load' });
      
      const pdfBuffer = await page.pdf({
        format: 'A4',
        printBackground: true,
        displayHeaderFooter: true,
        headerTemplate: `
          <div style="font-size: 9px; color: #9ca3af; padding: 0 20mm; width: 100%; display: flex; justify-content: space-between; font-family: 'Inter', sans-serif;">
            <span class="title"></span>
            <span class="date"></span>
          </div>
        `,
        footerTemplate: `
          <div style="font-size: 9px; color: #9ca3af; padding: 0 20mm; width: 100%; display: flex; justify-content: space-between; font-family: 'Inter', sans-serif; border-top: 1px solid #f3f4f6; padding-top: 4px;">
            <span>Generated by Modern Tech-Driven Classroom</span>
            <span>Page <span class="pageNumber"></span> of <span class="totalPages"></span></span>
          </div>
        `,
        margin: {
          top: '20mm',
          right: '20mm',
          bottom: '20mm',
          left: '20mm'
        }
      });

      return Buffer.from(pdfBuffer);
    } finally {
      await browser.close();
    }
  }
}
